/**
 * AI Summary plugin handler.
 * Generates a summary of the ticket conversation and adds it as an internal note.
 * In production, this would call an LLM API (e.g. OpenAI, Anthropic) to generate
 * the summary and then post it as a ticket note.
 */

import type { PluginHookContext, PluginHandlerResult } from '../../types';

function buildPrompt(
  subject: string,
  messages: Array<Record<string, unknown>>,
  maxTokens: number
): string {
  const messageLines = messages.map((m, i) => {
    const from = (m.from as string) || (m.author as string) || 'Unknown';
    const body = (m.body as string) || (m.text as string) || '';
    return `[${i + 1}] ${from}: ${body}`;
  });

  return [
    `Summarize the following support ticket conversation in under ${maxTokens} tokens.`,
    `Subject: ${subject}`,
    '',
    ...messageLines,
  ].join('\n');
}

export async function handle(context: PluginHookContext): Promise<PluginHandlerResult> {
  const { event, data, config } = context;
  const cfg = config ?? {};

  if (event !== 'ticket.resolved') {
    return { ok: true, data: { skipped: true, reason: `Unsupported event: ${event}` } };
  }

  const ticketId = (data.ticketId as string) || 'unknown';
  const subject = (data.subject as string) || 'No subject';
  const messages = (data.messages as Array<Record<string, unknown>>) || [];
  const maxTokens = (cfg.maxTokens as number) || 150;
  const model = (cfg.model as string) || 'gpt-4o-mini';

  if (messages.length === 0) {
    return {
      ok: true,
      data: {
        skipped: true,
        reason: 'No messages to summarize',
        ticketId,
      },
    };
  }

  const prompt = buildPrompt(subject, messages, maxTokens);

  // In production: POST to LLM API and then add result as internal note
  return {
    ok: true,
    data: {
      action: 'generate_summary',
      ticketId,
      model,
      maxTokens,
      messageCount: messages.length,
      prompt,
      // In production, the summary would be generated by the LLM
      note: `[AI Summary] Conversation summary for ticket ${ticketId} (${messages.length} messages, model: ${model})`,
    },
  };
}
