/**
 * Dual-runtime check for TechnoClass::Per_Cell_Process discovery.
 *
 * In SCU10EA a player-controlled BadGuy 3TNK moves through live visible fog
 * generated by player-controlled/allied sight. C++ marks the 3TNK
 * IsDiscoveredByPlayer from TechnoClass::Per_Cell_Process(PCP_END) because its
 * current cell is Map[cell].IsVisible. A Greek HUNT 2TNK can then target and
 * approach it on tick 135. TS used to keep the 3TNK hidden unless strict
 * PlayerPtr sight or a previously mapped cell saw it, delaying the HUNT target.
 */
import { afterAll, beforeAll, describe, expect, it } from 'vitest';

import {
  ensureParityServer,
  isDevServerAvailable,
  stepBoth,
  stopParityServer,
  withDualScenario,
  type ParityServerHandle,
} from './dual-runtime-test-utils.js';

const serverUp = isDevServerAvailable();
let serverHandle: ParityServerHandle | undefined;

type EvalPage = {
  evaluate<T, A>(fn: (arg: A) => T, arg: A): Promise<T>;
};

function adapterPage(adapter: unknown): EvalPage {
  const page = (adapter as { page?: EvalPage }).page;
  if (!page) throw new Error('Adapter page is not available');
  return page;
}

async function wasmScu10Snapshot(adapter: unknown) {
  return adapterPage(adapter).evaluate(() => {
    const state = JSON.parse((window as any).Module.ccall('agent_get_state', 'string', [], []));
    const units = [...(state.units ?? []), ...(state.enemies ?? [])];
    const scanner = units.find((u: any) =>
      u.t === '2TNK' && u.house === 'Greece' && u.cx === 99 && u.cy === 59);
    const target = units.find((u: any) =>
      u.t === '3TNK' && u.house === 'BadGuy' && u.cx === 113 && u.cy === 60);
    if (!scanner) throw new Error('C++ SCU10EA Greek 2TNK scanner not found');
    if (!target) throw new Error('C++ SCU10EA BadGuy 3TNK target not found');
    return {
      tick: state.tick,
      scanner: {
        lx: scanner.lx,
        ly: scanner.ly,
        mission: scanner.m,
        missionTimer: scanner.mt,
        isDriving: scanner.drv === true,
        targetLX: scanner.tlx ?? null,
        targetLY: scanner.tly ?? null,
        navLX: scanner.nlx ?? null,
        navLY: scanner.nly ?? null,
      },
      target: {
        lx: target.lx,
        ly: target.ly,
        discoveredByPlayer: target.dp === true,
        visible: target.vis === true,
        mapped: target.map === true,
      },
    };
  }, undefined);
}

async function tsScu10Snapshot(adapter: unknown) {
  return adapterPage(adapter).evaluate(() => {
    const game = (window as any).__agentGame;
    const scanner = game.entities.find((e: any) =>
      e.type === '2TNK' && e.house === 'Greece' && e.cell.cx === 99 && e.cell.cy === 59);
    const target = game.entities.find((e: any) =>
      e.type === '3TNK' && e.house === 'BadGuy' && e.cell.cx === 113 && e.cell.cy === 60);
    if (!scanner) throw new Error('TS SCU10EA Greek 2TNK scanner not found');
    if (!target) throw new Error('TS SCU10EA BadGuy 3TNK target not found');
    return {
      tick: game.tick,
      scanner: {
        lx: scanner.leptonX,
        ly: scanner.leptonY,
        mission: scanner.mission,
        missionTimer: scanner.missionTimer,
        isDriving: scanner.isDriving === true,
        targetLX: scanner.target?.leptonX ?? null,
        targetLY: scanner.target?.leptonY ?? null,
        navLX: scanner.moveTarget?.lx ?? null,
        navLY: scanner.moveTarget?.ly ?? null,
      },
      target: {
        lx: target.leptonX,
        ly: target.leptonY,
        discoveredByPlayer: game.discoveredEntityIds.has(target.id),
        visible: game.map.getVisibility(target.cell.cx, target.cell.cy) === 2,
        mapped: game.map.getVisibility(target.cell.cx, target.cell.cy) > 0,
      },
    };
  }, undefined);
}

describe.skipIf(!serverUp)('Dual runtime C++ parity: SCU10 visible-cell discovery', () => {
  beforeAll(async () => {
    serverHandle = await ensureParityServer();
  }, 180_000);

  afterAll(async () => {
    await stopParityServer(serverHandle);
  }, 20_000);

  it('discovers the BadGuy 3TNK from live visible fog before the Greek 2TNK HUNT scan', async () => {
    await withDualScenario('SCU10EA', async (handle) => {
      await handle.ts.syncRngSeed(handle.wasmState.rngState!);

      await stepBoth(handle, 134);
      const cpp134 = await wasmScu10Snapshot(handle.wasm);
      const ts134 = await tsScu10Snapshot(handle.ts);

      expect(ts134.tick).toBe(cpp134.tick);
      expect(cpp134.target.discoveredByPlayer).toBe(true);
      expect(ts134.target.mapped).toBe(true);
      expect(ts134.target.discoveredByPlayer).toBe(cpp134.target.discoveredByPlayer);

      await stepBoth(handle, 1);
      const cpp135 = await wasmScu10Snapshot(handle.wasm);
      const ts135 = await tsScu10Snapshot(handle.ts);

      expect(ts135.tick).toBe(cpp135.tick);
      expect(ts135.scanner.mission).toBe('HUNT');
      expect(cpp135.scanner.mission).toBe(14);
      expect(ts135.scanner.isDriving).toBe(cpp135.scanner.isDriving);
      expect(ts135.scanner.lx).toBe(cpp135.scanner.lx);
      expect(ts135.scanner.ly).toBe(cpp135.scanner.ly);
      expect(ts135.scanner.targetLX).toBe(cpp135.scanner.targetLX);
      expect(ts135.scanner.targetLY).toBe(cpp135.scanner.targetLY);
      expect(ts135.scanner.navLX).toBe(cpp135.scanner.navLX);
      expect(ts135.scanner.navLY).toBe(cpp135.scanner.navLY);
    }, { wasmSeed: 0 });
  }, 180_000);
});
